### ISSUE TITLE
Suggestion at Representing Resources > jq

### ISSUE THREAD

**Issue by jmaziarz** [abuiles/json-api-by-example-errata#4]
On page 10 (PDF):

> For homebrew users, it can be installed with brew install, for other platforms there is more information in the following page https://stedolan.github.io/jq/download/11

The sentence suggests that "homebrew" is a platform. As a suggestion:

> For Mac users, jq can be installed using Homebrew (provide a link as a footnote). For all other platforms, see https://stedolan.github.io/jq/download/11.

**Comment by abuiles** [comment]
Thanks Jeremy! I follow your recommendation. I think people who knows what `homebrew` is might infer `brew install jq` so I won't add it. Also it is listed in the download  page :)
